server:
  port: 8181
  servlet:
        context-path: /poops

spring:
  application:
    name: Poops

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  datasource:
    url: "jdbc:mysql://localhost:3306/insta"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: thanhdeptrai

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

  rabbitmq:
    host: rabbitmq
    port: 5672
    stomp:
      relay:
        host: rabbitmq
        port: 61613
        login: guest
        passcode: guest

  mail:
    from: 
    host: smtp.gmail.com
    port: 587
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

jwt:
  accessKey: "hPYEmmjvdCO7QG73HF3kPYbv6yLKAvGzbtHZC/JS3tKhyyP9rM/RG6pdJEozyJJsFkjxkuwe/Ypx57rf7wMbZumA4Dg+6bkGUyWIlOlsdHs="
  refreshKey: "PYEmmjvdCO7QG73HF3kPYbv6yLKAvGzbtHZC/JS3tKhyyP9rM/RG6pdJEozyJJsFkjxkuwe/Ypx57rf7wMbZumA4Dg+6bkGUyWIlOlsdHs="
  accessExpiryMinutes: 1800000   # 30 phut
  refreshExpiryMinutes: 43200000   # 30 ngay

app:
  file:
    storage-dir: D:/github.com/Insta/backend/upload
    download-prefix: http://localhost:8181/poops/api/v1/files/media/download
