server:
  port: 8181
#  servlet:
#        context-path: /poops
  error:
    whitelabel:
      enabled: false

logging:
#  file:
#    name: ./log/application.log
  level:
#    root: ERROR
    init:
      upinmcse:
        backend:
          config:
            init:
              LoggingFilter: INFO
    org:
      springframework:
        security: TRACE

spring:
  application:
    name: Poops

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/insta}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  mail:
    from: ${MAIL}
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

jwt:
  secretKey: ${JWT_SIGNERKEY}
  accessExpiryMinutes: 7200
  refreshExpiryMinutes: 72000

app:
  file:
    storage-dir: D:/github.com/Insta/backend/upload
    download-prefix: http://localhost:8181/api/v1/files/media/download

outbound:
  identity:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    redirect-uri: "http://localhost:3000/authentication"

minio:
  endpoint: http://localhost:9000
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket-name: ${MINIO_BUCKET_NAME:insta}